server:
  port: 8080
spring:
  mail:
    host: smtp.163.com
    username: 13755717949@163.com
    password: Aa123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
